GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "user" : "test",
    "title" : "title",
    "content" : "content",
    "password" : "test1234"
}

###

GET http://localhost:3000/posts/63ee6a817e7567416d66fa94

###

PATCH http://localhost:3000/posts/63ee6a817e7567416d66fa94
Content-Type: application/json

{
    "user": "edit test",
    "password": "test1234"
}

###

DELETE http://localhost:3000/posts/63ee6a817e7567416d66fa94
Content-Type: application/json

{
    "password" : "test1234"
}

###
GET http://localhost:3000/comments

###

POST http://localhost:3000/comments/63ef5b26bcbc468a6e2f9b92
Content-Type: application/json

{
    "user":"comment test2",
    "content":"test",
    "password":"test123"
}

###

GET http://localhost:3000/comments/63ef5b26bcbc468a6e2f9b92

###

PATCH http://localhost:3000/comments/63ef5bbff550d5005f829e82
Content-Type: application/json

{
    "content":"edit test",
    "password":"test12"
}

###

Delete http://localhost:3000/comments/63ef665de7228ee5c88d4e9a
Content-Type: application/json

{
    "password":"test123"
}